const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const transcript=$('#transcript'), count=$('#charCount'), error=$('#inputError'), results=$('#results'), empty=$('#emptyState'), badge=$('#statusBadge');
const sample=`User reports repeated Microsoft Outlook credential prompts after a password reset. Issue started this morning and affects Outlook desktop only; Outlook Web works normally. Technician verified network connectivity, cleared cached credentials in Credential Manager, removed and re-added the work account, and restarted Outlook. The profile then authenticated successfully and mail synchronized. User confirmed they can send and receive email without another prompt. No further action is required.`;
transcript.addEventListener('input',()=>{count.textContent=`${transcript.value.length.toLocaleString()} / 12,000`;error.textContent=''});
$('#sampleBtn').onclick=()=>{transcript.value=sample;transcript.dispatchEvent(new Event('input'));transcript.focus()};
$('#clearBtn').onclick=()=>{transcript.value='';transcript.dispatchEvent(new Event('input'));results.classList.add('hidden');empty.classList.remove('hidden');badge.textContent='Awaiting input';badge.classList.remove('ready')};
function sentenceList(text){return text.replace(/\n+/g,' ').split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(s=>s.length>15)}
function pick(sentences,words){return sentences.filter(s=>words.some(w=>s.toLowerCase().includes(w))).slice(0,5)}
function clean(s){return s.replace(/^(user|agent|technician|caller|customer)\s*[:\-]\s*/i,'').trim()}
function makeNotes(text){const s=sentenceList(text);const issue=pick(s,['report','issue','problem','unable','error','fail','prompt','affect'])[0]||s[0]||text;const actions=pick(s,['verified','checked','cleared','removed','restarted','reset','updated','installed','tested','re-added','configured']);const outcome=pick(s,['confirmed','success','resolved','working','synchronized','restored','can send','no further']);const work=[`Issue: ${clean(issue)}`,actions.length?`Actions performed:\n${actions.map(x=>'• '+clean(x)).join('\n')}`:'Actions performed:\n• Reviewed the reported symptoms and available incident context.',`Findings: ${clean((outcome[0]||s[s.length-1]||'The available information was reviewed.'))}`].join('\n\n');const resolution=[`Resolution: ${clean((outcome[0]||'The reported issue was addressed based on the documented troubleshooting.'))}`,outcome[1]?`Verification: ${clean(outcome[1])}`:'Verification: Confirmed the outcome using the information provided in the transcript.',`Closure: ${/no further action|resolved|confirmed/i.test(text)?'No additional action is required at this time.':'Review the result with the user and close the ticket after confirmation.'}`].join('\n\n');return{work,resolution}}
$('#generateBtn').onclick=()=>{const text=transcript.value.trim();if(text.length<30){error.textContent='Add a little more incident detail before generating notes.';transcript.focus();return}const btn=$('#generateBtn');btn.disabled=true;btn.querySelector('span').textContent='✦ Structuring documentation…';setTimeout(()=>{const n=makeNotes(text);$('#workNotes').textContent=n.work;$('#resolutionNotes').textContent=n.resolution;empty.classList.add('hidden');results.classList.remove('hidden');badge.textContent='Ready';badge.classList.add('ready');btn.disabled=false;btn.querySelector('span').textContent='✦ Generate documentation';showToast('Documentation generated')},550)};
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast('Copied to clipboard')}catch{showToast('Copy failed — select the text manually')}}
$$('.copy').forEach(b=>b.onclick=()=>copyText($('#'+b.dataset.target).innerText));
$('#copyAllBtn').onclick=()=>copyText(`WORK NOTES\n\n${$('#workNotes').innerText}\n\nRESOLUTION NOTES\n\n${$('#resolutionNotes').innerText}`);
$('#downloadBtn').onclick=()=>{const body=`DXC DOCUMENTATION\nGenerated: ${new Date().toLocaleString()}\n\nWORK NOTES\n${$('#workNotes').innerText}\n\nRESOLUTION NOTES\n${$('#resolutionNotes').innerText}\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/plain'}));a.download=`dxc-documentation-${new Date().toISOString().slice(0,10)}.txt`;a.click();URL.revokeObjectURL(a.href);showToast('Download created')};
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));
