"use client";

import * as React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  FileText,
  Mail,
  Lock,
  Wifi,
  Printer,
  ArrowUpRight,
  User as UserIcon,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { relativeTime } from "@/lib/utils";

type ActivityItem = {
  id: string;
  title: string;
  agent: string;
  initials: string;
  icon: React.ElementType;
  iconTone: "blue" | "orange" | "purple" | "green" | "red";
  priority: "Critical" | "High" | "Medium" | "Low";
  tags: string[];
  createdAt: string;
};

const recentItems: ActivityItem[] = [
  {
    id: "1",
    title: "Outlook keeps prompting for credentials post-migration",
    agent: "Alex Carter",
    initials: "AC",
    icon: Mail,
    iconTone: "blue",
    priority: "High",
    tags: ["Outlook", "M365", "Credentials"],
    createdAt: new Date(Date.now() - 4 * 60000).toISOString(),
  },
  {
    id: "2",
    title: "VPN connection fails with error 691 for remote user",
    agent: "Priya Shah",
    initials: "PS",
    icon: Wifi,
    iconTone: "purple",
    priority: "High",
    tags: ["VPN", "Remote Access"],
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: "3",
    title: "AD account locked after 5 failed login attempts",
    agent: "Jordan Lee",
    initials: "JL",
    icon: Lock,
    iconTone: "orange",
    priority: "Medium",
    tags: ["Active Directory", "Account"],
    createdAt: new Date(Date.now() - 28 * 60000).toISOString(),
  },
  {
    id: "4",
    title: "Default printer keeps switching on shared workstation",
    agent: "Sam Rivera",
    initials: "SR",
    icon: Printer,
    iconTone: "green",
    priority: "Low",
    tags: ["Print", "Workstation"],
    createdAt: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: "5",
    title: "Excel query refresh returns DB connection timeout",
    agent: "Alex Carter",
    initials: "AC",
    icon: FileText,
    iconTone: "red",
    priority: "Medium",
    tags: ["Excel", "Database"],
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
  },
];

const toneMap = {
  blue: "from-sky-500/20 to-sky-500/0 text-sky-600 dark:text-sky-300",
  orange: "from-orange-500/20 to-orange-500/0 text-orange-600 dark:text-orange-300",
  purple: "from-violet-500/20 to-violet-500/0 text-violet-600 dark:text-violet-300",
  green: "from-emerald-500/20 to-emerald-500/0 text-emerald-600 dark:text-emerald-300",
  red: "from-rose-500/20 to-rose-500/0 text-rose-600 dark:text-rose-300",
};

const priorityVariant = {
  Critical: "destructive",
  High: "warning",
  Medium: "default",
  Low: "secondary",
} as const;

export function RecentActivity() {
  return (
    <section className="mx-auto w-full max-w-[1440px] px-6 pb-16 md:px-10">
      <div className="grid gap-6 lg:grid-cols-3">
        {/* Recent activity timeline */}
        <Card className="lg:col-span-2">
          <CardHeader className="flex flex-row items-center justify-between space-y-0">
            <div>
              <CardTitle className="text-base md:text-lg">
                Recent Activity
              </CardTitle>
              <CardDescription>
                Latest documentation generated by your team
              </CardDescription>
            </div>
            <Button asChild variant="outline" size="sm">
              <Link href="/history">
                View all <ArrowUpRight className="h-3.5 w-3.5" />
              </Link>
            </Button>
          </CardHeader>
          <CardContent>
            <ol className="relative space-y-5 before:absolute before:left-[19px] before:top-2 before:h-[calc(100%-16px)] before:w-px before:bg-border/70">
              {recentItems.map((item, i) => {
                const Icon = item.icon;
                return (
                  <motion.li
                    key={item.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.35, delay: i * 0.05 }}
                    className="relative pl-12"
                  >
                    <div
                      className={`absolute left-0 top-1 inline-flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br ${toneMap[item.iconTone]} ring-1 ring-border/60 shadow-sm`}
                    >
                      <Icon className="h-4.5 w-4.5" strokeWidth={2.1} />
                    </div>
                    <div className="flex flex-col gap-2 rounded-2xl border border-transparent p-3 transition-colors hover:bg-accent/5 hover:border-border/50">
                      <div className="flex flex-wrap items-start justify-between gap-2">
                        <Link
                          href={`/history/${item.id}`}
                          className="text-sm font-semibold leading-snug hover:text-primary"
                        >
                          {item.title}
                        </Link>
                        <Badge variant={priorityVariant[item.priority]}>
                          {item.priority}
                        </Badge>
                      </div>
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="inline-flex items-center gap-1.5 text-[11.5px] text-muted-foreground">
                          <Avatar className="h-5 w-5 ring-1 ring-border/60">
                            <AvatarFallback className="text-[9.5px]">
                              {item.initials}
                            </AvatarFallback>
                          </Avatar>
                          <span className="font-medium text-foreground/80">
                            {item.agent}
                          </span>
                        </span>
                        <span className="text-[11.5px] text-muted-foreground">
                          {relativeTime(item.createdAt)}
                        </span>
                      </div>
                      <div className="flex flex-wrap gap-1.5">
                        {item.tags.map((t) => (
                          <Badge
                            key={t}
                            variant="secondary"
                            className="text-[10.5px]"
                          >
                            {t}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  </motion.li>
                );
              })}
            </ol>
          </CardContent>
        </Card>

        {/* Team / personal summary */}
        <Card>
          <CardHeader className="space-y-1">
            <CardTitle className="text-base md:text-lg">
              Personal Productivity
            </CardTitle>
            <CardDescription>Your last 7 days</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <WeekBars />
            <div className="grid grid-cols-2 gap-3">
              <StatMini label="Docs written" value="42" />
              <StatMini label="Avg quality" value="A+" />
              <StatMini label="Fastest doc" value="48s" />
              <StatMini label="Articles" value="6" />
            </div>
            <div className="rounded-2xl border border-border/70 bg-dxc-gradient-soft p-4">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/80 ring-1 ring-border/60 dark:bg-card">
                  <UserIcon className="h-5 w-5 text-gradient-dxc" />
                </div>
                <div>
                  <div className="text-sm font-semibold">
                    You&apos;re in the top 12%
                  </div>
                  <div className="text-[11.5px] text-muted-foreground">
                    of agents this week across EMEA
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}

function WeekBars() {
  const days = [
    { d: "Mon", v: 6 },
    { d: "Tue", v: 9 },
    { d: "Wed", v: 5 },
    { d: "Thu", v: 11 },
    { d: "Fri", v: 7 },
    { d: "Sat", v: 2 },
    { d: "Sun", v: 2 },
  ];
  const max = Math.max(...days.map((x) => x.v));
  return (
    <div>
      <div className="flex h-28 items-end gap-2">
        {days.map((x, i) => (
          <div key={x.d} className="flex flex-1 flex-col items-center gap-2">
            <motion.div
              initial={{ height: 0 }}
              animate={{ height: `${(x.v / max) * 100}%` }}
              transition={{
                duration: 0.6,
                delay: 0.05 * i,
                ease: "easeOut",
              }}
              className="w-full rounded-t-lg bg-dxc-gradient"
              style={{ minHeight: "4px" }}
            />
          </div>
        ))}
      </div>
      <div className="mt-2 flex gap-2 text-[10.5px] text-muted-foreground">
        {days.map((x) => (
          <div key={x.d} className="flex-1 text-center font-medium">
            {x.d}
          </div>
        ))}
      </div>
    </div>
  );
}

function StatMini({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border/70 bg-background/60 p-3">
      <div className="text-[10.5px] uppercase tracking-wider text-muted-foreground">
        {label}
      </div>
      <div className="mt-1 text-lg font-bold tracking-tight">{value}</div>
    </div>
  );
}
