import { PlaceholderPage } from "@/components/layout/PlaceholderPage";

export default function HistoryPage() {
  return (
    <PlaceholderPage
      eyebrow="History"
      title="Documentation History"
      description="Searchable archive of every analysis generated by your team."
      hint="Coming in Phase 5 — Supabase-connected search, filters and detail views."
      status="In Progress"
    />
  );
}
